name: ci-cd-pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - teja

jobs:
  ci-cd-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout to Branch'
        uses: actions/checkout@v4

      - name: "Setting up Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: "Install Maven"
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: "3.8.2"

      - name: "Build Jar with Maven"
        run: |
          #!/bin/bash
          
          mvn clean package

        shell: bash

      - name: Install Tomcat
        run: |
          wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz
          sudo mkdir -p /opt/tomcat
          sudo tar xzf apache-tomcat-11.0.2.tar.gz -C /opt/tomcat --strip-components=1
          sudo chmod +x /opt/tomcat/bin/*.sh

      - name: "Start TOMCAT"
        run: |
          sudo chown -R $USER:$USER /opt/tomcat
          sudo chmod -R 755 /opt/tomcat
          sudo chmod -R 777 /opt/tomcat/logs /opt/tomcat/temp /opt/tomcat/work
          /opt/tomcat/bin/startup.sh
          sleep 10

      - name: Deploy to Tomcat
        run: |
          WAR_FILE=$(ls target/*.war | head -n 1) # Get the first .war file
          curl --upload-file "$WAR_FILE" \
          --user ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} \
          http://localhost:8080/manager/text/deploy?path=/jenkins_calci-1.0-SNAPSHOT



#      - name: "Building Docker Image"
#        run: |
#          #!/bin/bash
#          docker build -t ci-cd .
#
#        shell: bash



#      - name: "Setup GCP SDK"
#        uses: "google-github-actions/setup-gcloud@v2"
#
#      - name: "setup service account"
#        uses: "google-github-actions/auth@v2"
#        with:
#          credentials_json: "${{ secrets.SERVICE_ACCOUNT_CREDS }}"

#      - name: "Setting up Docker credentials"
#        run: |
#          #!/bin/bash
#          gcloud auth configure docker us-central1-docker.pkg.dev
#
#        shell: bash

#      - name: "Upload image to GCP artifacts"
#        run: |
#          #!/bin/bash
#
#          docker tag ci-cd:latest us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/ci-cd:latest
#          docker push us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/ci-cd:latest